import { request, type RequestConfig, type RequestContext } from "@/adapter";

/**
 * Returns options for a client library
 * @path `/gen/clients/{language}`
 */
export function getClientOptions(options: {
  pathParams: API.CustomizeResponseWrapper.Clients.GetClientOptions.PathParams;
  headers?: Record<string, any>;
  config?: RequestConfig;
  context?: RequestContext;
}) {
  return request<API.CustomizeResponseWrapper.Clients.GetClientOptions.Response>(
    "get",
    `/gen/clients/${options.pathParams.language}`,
    options,
  );
}

/**
 * Accepts a `GeneratorInput` options map for spec location and generation options
 * @summary Generates a client library
 * @path `/gen/clients/{language}`
 */
export function generateClient(options: {
  pathParams: API.CustomizeResponseWrapper.Clients.GenerateClient.PathParams;
  headers?: Record<string, any>;
  body?: API.CustomizeResponseWrapper.Clients.GenerateClient.Body;
  config?: RequestConfig;
  context?: RequestContext;
}) {
  return request<API.CustomizeResponseWrapper.Clients.GenerateClient.Response>(
    "post",
    `/gen/clients/${options.pathParams.language}`,
    options,
  );
}

/**
 * Gets languages supported by the client generator
 * @path `/gen/clients`
 */
export function clientOptions(options?: {
  headers?: Record<string, any>;
  config?: RequestConfig;
  context?: RequestContext;
}) {
  return request<API.CustomizeResponseWrapper.Clients.ClientOptions.Response>(
    "get",
    "/gen/clients",
    options || {},
  );
}

/**
 * A valid `fileId` is generated by the `/clients/{language}` or `/servers/{language}` POST operations.  The fileId code can be used just once, after which a new `fileId` will need to be requested.
 * @summary Downloads a pre-generated file
 * @path `/gen/download/{fileId}`
 */
export function downloadFile(options: {
  pathParams: API.CustomizeResponseWrapper.Clients.DownloadFile.PathParams;
  headers?: Record<string, any>;
  config?: RequestConfig;
  context?: RequestContext;
}) {
  return request<API.CustomizeResponseWrapper.Clients.DownloadFile.Response>(
    "get",
    `/gen/download/${options.pathParams.fileId}`,
    options,
  );
}
